# Generated by Django 4.1.4 on 2023-04-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user_id",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=30)),
                ("gender", models.CharField(max_length=6)),
                ("dob", models.DateField()),
                ("email", models.EmailField(max_length=250)),
            ],
        ),
    ]
