# Generated by Django 4.2 on 2023-04-26 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal_details',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.user_id')),
                ('family_history', models.CharField(max_length=1000)),
                ('treatment', models.CharField(max_length=1000)),
                ('mental_health_condition', models.CharField(max_length=1000)),
                ('phy_health_condition', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
    ]
