# Generated by Django 4.2.5 on 2023-09-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_personal_details_quizresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresponse',
            name='answers',
            field=models.TextField(),
        ),
    ]
